version: "3.9"
services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Tekken55%
      POSTGRES_DB: tiendavideojuegos # Crea la base de datos al iniciar
      PGDATA: /data/postgres
    volumes:
      - ./database/postgres:/data/postgres # Persistencia
    ports:
      - "5432:5432" # Solo para acceso desde el host
    networks:
      - postgres_net
    restart: unless-stopped

  app:
    build: ./backend # Ruta al Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - postgres_net
    volumes:
      - ./backend:/usr/src/app # Monta la carpeta backend
    working_dir: /usr/src/app # Establece el directorio de trabajo
    command: npm run dev # Ejecuta tu script de desarrollo

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./database/pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres_net
    restart: unless-stopped

networks:
  postgres_net:
    driver: bridge
